$(document).ready(function(){
  $('#open').click(function(){
    $('.container').css("opacity","1");
    $('.container').css("pointer-events","auto");
  });
  $('#login').click(function(){
    $('.container').css("opacity","0");
    $('.container').css("pointer-events","none");
  });
});
